name: CI

on:
  push:
    branches: ["main"]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Lint
        run: npm run lint
        working-directory: ./frontend

      - name: Prettier Check
        run: npm run format:check
        working-directory: ./frontend

      - name: Typescript Check
        run: npm run type-check
        working-directory: ./frontend

      - name: Build Project
        run: npm run build
        working-directory: ./frontend

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Lint
        run: npm run lint
        working-directory: ./backend

      - name: Prettier Check
        run: npm run format:check
        working-directory: ./backend

      - name: Typescript Check
        run: npm run type-check
        working-directory: ./backend

      - name: Jest Test
        run: npm run test:ci
        working-directory: ./backend

      - name: Build Project
        run: npm run build
        working-directory: ./backend
